'use strict'
import HtmlWebpackPlugin from 'html-webpack-plugin'
export default env => {
  return {
    plugins: [
      new HtmlWebpackPlugin({
        filename: 'index.html',
        template: __dirname + '/../sources/index.html',
        inject: false,
        minify: {
          caseSensitive: false,
          collapseBooleanAttributes: env.production,
          collapseWhitespace: env.production,
          collapseInlineTagWhitespace: env.production,
          conservativeCollapse: false,
          decodeEntities: env.production,
          html5: true,
          includeAutoGeneratedTags: false,
          keepClosingSlash: false,
          minifyCSS: env.production,
          minifyJS: env.production,
          minifyURLs: env.production,
          preserveLineBreaks: !env.production,
          preventAttributesEscaping: false,
          processConditionalComments: false,
          quoteCharacter: '\'',
          removeAttributeQuotes: env.production,
          removeComments: env.production,
          removeEmptyAttributes: false,
          removeEmptyElements: false,
          removeOptionalTags: env.production,
          removeRedundantAttributes: env.production,
          removeScriptTypeAttributes: env.production,
          removeStyleLinkTypeAttributes: env.production,
          removeTagWhitespace: false,
          sortAttributes: env.production,
          sortClassName: env.production,
          trimCustomFragments: false,
          useShortDoctype: false
        },
        cache: true
      })
    ]
  }
}
